### ISSUE TITLE
romanceChanceFactor is fixed at 0.15

### ISSUE THREAD

**Issue by KochFolie** [LordSicarious/sic-cospousal-relations#1]
This line appears to be setting the romanceChanceFactor to 0.15 for almost every colonist relationship:
https://github.com/LordSicarious/sic-cospousal-relations/blob/68fdba0c97ed0e524acff926dc605d00e0d847ec/Source/HarmonyPatches/Postfix_SecondaryLovinChanceFactor.cs#L12
After disabling your mod, my colony starts romancing again. Please fix. :)

**Comment by LordSicarious** [comment]
Oops, already have that fixed on my local version, will push fix tonight.

**Comment by LordSicarious** [comment]
Pushed the fix, it now only applies to results that fall below the minimum, and also should actually work.

**Comment by KochFolie** [comment]
Thanks, seems to be working again!
